version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
       - ALLOW_EMPTY_PASSWORD=yes
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'